//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Inputs/PlayerInputSystem.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputSystem: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputSystem()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputSystem"",
    ""maps"": [
        {
            ""name"": ""CameraControl"",
            ""id"": ""0716b70c-8b8d-4018-8a7a-059fe7540a18"",
            ""actions"": [
                {
                    ""name"": ""Camera_move"",
                    ""type"": ""Value"",
                    ""id"": ""a223cd23-c4a3-4db0-9297-0ad0c7acf540"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Camera_rotate_toggle"",
                    ""type"": ""Button"",
                    ""id"": ""3764a827-3f57-459c-b333-317afef70bb3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Camera_rotate"",
                    ""type"": ""Value"",
                    ""id"": ""31de0dc5-947e-49ad-afdb-e2cd669d78b2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Camera_zoom"",
                    ""type"": ""Value"",
                    ""id"": ""0d787251-a536-42b3-bca9-fa7e83ff9e4c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Camera_rotate_dpad"",
                    ""type"": ""Value"",
                    ""id"": ""723f54e5-a83c-46b0-8aaa-a29485409489"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""99f60732-a1d5-441f-9dbc-88494e189e09"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera_rotate_toggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41c5a10d-7e84-4b5b-a017-7d8ab9f15c12"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera_rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""080d28a8-cb06-4a24-9310-681a789c89e7"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera_move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""84065962-4768-47ae-9873-506e8fea0cd4"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera_move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""33cb8f96-4540-40b4-b9cb-771275db94c0"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera_move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7fb15e83-7483-4e09-9b5e-91c1c4a7d9b4"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera_move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5557956c-d9b2-4a4e-a538-21acb9467021"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera_move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""236d82c3-880e-47e4-b8e7-42a709931f65"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera_move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2cd3213c-1bd7-4171-bda2-d30ecd027527"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera_move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c72479cd-05d7-43c4-9bd1-9a646a40bbf8"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera_move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""54d0e0b2-a8b6-4385-ac64-2a349e930ba5"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera_move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e84afbf0-48f5-4bc0-a76c-a144124a8a8d"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera_move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""852ee3e9-8b6a-441e-afb8-ddac33e13adc"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera_move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bbdb7f82-1a50-4b80-b05c-6ae6bca6e70c"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2"",
                    ""groups"": """",
                    ""action"": ""Camera_zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""903ec39e-1605-4462-bfe9-b212d3406137"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera_zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70189130-7aa3-4689-8b03-8ed094dfd2d3"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera_rotate_dpad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CameraControl
        m_CameraControl = asset.FindActionMap("CameraControl", throwIfNotFound: true);
        m_CameraControl_Camera_move = m_CameraControl.FindAction("Camera_move", throwIfNotFound: true);
        m_CameraControl_Camera_rotate_toggle = m_CameraControl.FindAction("Camera_rotate_toggle", throwIfNotFound: true);
        m_CameraControl_Camera_rotate = m_CameraControl.FindAction("Camera_rotate", throwIfNotFound: true);
        m_CameraControl_Camera_zoom = m_CameraControl.FindAction("Camera_zoom", throwIfNotFound: true);
        m_CameraControl_Camera_rotate_dpad = m_CameraControl.FindAction("Camera_rotate_dpad", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CameraControl
    private readonly InputActionMap m_CameraControl;
    private List<ICameraControlActions> m_CameraControlActionsCallbackInterfaces = new List<ICameraControlActions>();
    private readonly InputAction m_CameraControl_Camera_move;
    private readonly InputAction m_CameraControl_Camera_rotate_toggle;
    private readonly InputAction m_CameraControl_Camera_rotate;
    private readonly InputAction m_CameraControl_Camera_zoom;
    private readonly InputAction m_CameraControl_Camera_rotate_dpad;
    public struct CameraControlActions
    {
        private @PlayerInputSystem m_Wrapper;
        public CameraControlActions(@PlayerInputSystem wrapper) { m_Wrapper = wrapper; }
        public InputAction @Camera_move => m_Wrapper.m_CameraControl_Camera_move;
        public InputAction @Camera_rotate_toggle => m_Wrapper.m_CameraControl_Camera_rotate_toggle;
        public InputAction @Camera_rotate => m_Wrapper.m_CameraControl_Camera_rotate;
        public InputAction @Camera_zoom => m_Wrapper.m_CameraControl_Camera_zoom;
        public InputAction @Camera_rotate_dpad => m_Wrapper.m_CameraControl_Camera_rotate_dpad;
        public InputActionMap Get() { return m_Wrapper.m_CameraControl; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CameraControlActions set) { return set.Get(); }
        public void AddCallbacks(ICameraControlActions instance)
        {
            if (instance == null || m_Wrapper.m_CameraControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CameraControlActionsCallbackInterfaces.Add(instance);
            @Camera_move.started += instance.OnCamera_move;
            @Camera_move.performed += instance.OnCamera_move;
            @Camera_move.canceled += instance.OnCamera_move;
            @Camera_rotate_toggle.started += instance.OnCamera_rotate_toggle;
            @Camera_rotate_toggle.performed += instance.OnCamera_rotate_toggle;
            @Camera_rotate_toggle.canceled += instance.OnCamera_rotate_toggle;
            @Camera_rotate.started += instance.OnCamera_rotate;
            @Camera_rotate.performed += instance.OnCamera_rotate;
            @Camera_rotate.canceled += instance.OnCamera_rotate;
            @Camera_zoom.started += instance.OnCamera_zoom;
            @Camera_zoom.performed += instance.OnCamera_zoom;
            @Camera_zoom.canceled += instance.OnCamera_zoom;
            @Camera_rotate_dpad.started += instance.OnCamera_rotate_dpad;
            @Camera_rotate_dpad.performed += instance.OnCamera_rotate_dpad;
            @Camera_rotate_dpad.canceled += instance.OnCamera_rotate_dpad;
        }

        private void UnregisterCallbacks(ICameraControlActions instance)
        {
            @Camera_move.started -= instance.OnCamera_move;
            @Camera_move.performed -= instance.OnCamera_move;
            @Camera_move.canceled -= instance.OnCamera_move;
            @Camera_rotate_toggle.started -= instance.OnCamera_rotate_toggle;
            @Camera_rotate_toggle.performed -= instance.OnCamera_rotate_toggle;
            @Camera_rotate_toggle.canceled -= instance.OnCamera_rotate_toggle;
            @Camera_rotate.started -= instance.OnCamera_rotate;
            @Camera_rotate.performed -= instance.OnCamera_rotate;
            @Camera_rotate.canceled -= instance.OnCamera_rotate;
            @Camera_zoom.started -= instance.OnCamera_zoom;
            @Camera_zoom.performed -= instance.OnCamera_zoom;
            @Camera_zoom.canceled -= instance.OnCamera_zoom;
            @Camera_rotate_dpad.started -= instance.OnCamera_rotate_dpad;
            @Camera_rotate_dpad.performed -= instance.OnCamera_rotate_dpad;
            @Camera_rotate_dpad.canceled -= instance.OnCamera_rotate_dpad;
        }

        public void RemoveCallbacks(ICameraControlActions instance)
        {
            if (m_Wrapper.m_CameraControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICameraControlActions instance)
        {
            foreach (var item in m_Wrapper.m_CameraControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CameraControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CameraControlActions @CameraControl => new CameraControlActions(this);
    public interface ICameraControlActions
    {
        void OnCamera_move(InputAction.CallbackContext context);
        void OnCamera_rotate_toggle(InputAction.CallbackContext context);
        void OnCamera_rotate(InputAction.CallbackContext context);
        void OnCamera_zoom(InputAction.CallbackContext context);
        void OnCamera_rotate_dpad(InputAction.CallbackContext context);
    }
}
